# Generated by Django 5.2 on 2025-05-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0003_product_category_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Desconocida', max_length=255),
        ),
    ]
