# Generated by Django 5.2 on 2025-05-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0005_remove_product_brand_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Desconocida', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Desconocida', max_length=255),
        ),
    ]
