# Generated by Django 5.2 on 2025-07-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0007_processedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedpdf',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
